using System.Collections.Generic;

namespace Athanor.Infra
{
    /// Localización mínima: es como idioma base, estructura lista para agregar en.
    public static class Loc
    {
        static readonly Dictionary<string, string> es = new Dictionary<string, string>
        {
            // Elementos
            { "el_tierra", "Tierra" }, { "el_agua", "Agua" }, { "el_fuego", "Fuego" },
            { "el_aire", "Aire" }, { "el_barro", "Barro" }, { "el_lava", "Lava" },
            { "el_polvo", "Polvo" }, { "el_vapor", "Vapor" }, { "el_niebla", "Niebla" },
            { "el_energia", "Energía" }, { "el_piedra", "Piedra" }, { "el_metal", "Metal" },
            { "el_cristal", "Cristal" }, { "el_vida", "Vida" }, { "el_sal", "Sal" },
            { "el_mercurio", "Mercurio" }, { "el_azufre", "Azufre" }, { "el_oro", "Oro" },
            { "el_eter", "Éter" }, { "el_piedrafilosofal", "Piedra Filosofal" },
            // Generadores
            { "gen_aprendiz", "Aprendiz" }, { "gen_alambique", "Alambique" },
            { "gen_brasero", "Brasero" }, { "gen_fuelle", "Fuelle" },
            { "gen_crisol", "Crisol" }, { "gen_condensador", "Condensador" },
            { "gen_athanor", "Horno Athanor" }, { "gen_transmutador", "Transmutador" },
            // UI
            { "ui_esencia", "Esencia" },
            { "ui_transmutar_todo", "Transmutar todo" },
            { "ui_poder_click", "Poder de click" },
            { "ui_nivel", "Nv." },
            { "ui_coste", "Coste" },
            { "ui_update_titulo", "Actualización disponible" },
            { "ui_update_texto", "Hay una versión nueva del juego:" },
            { "ui_update_descargar", "Descargar" },
            { "ui_update_luego", "Más tarde" },
            { "ui_tab_lab", "Laborat." },
            { "ui_tab_ayudantes", "Ayudantes" },
            { "ui_tab_elementos", "Elementos" },
            { "ui_tab_logros", "Logros" },
            { "ui_tab_obra", "Gran Obra" },
            { "ui_tab_ajustes", "Ajustes" },
            { "ui_comprar", "Comprar" },
            { "ui_produce", "Produce" },
            { "ui_combina_solo", "Ejecuta la mejor receta conocida" },
            { "ui_desconocido", "???" },
            { "ui_combinar", "Combinar" },
            { "ui_vender", "Vender" },
            { "ui_nuevo_elemento", "¡Nuevo elemento!" },
            { "ui_receta_oculta", "Combina para descubrir" },
            { "ui_quintaesencia", "Quintaesencia" },
            { "ui_bonus_actual", "Bonus de producción:" },
            { "ui_prestigios", "Prestigios" },
            { "ui_prestigio_desc", "Reinicia tu progreso a cambio de Quintaesencia:\n+10% de producción permanente por punto." },
            { "ui_prestigio_boton", "Realizar la Gran Obra" },
            { "ui_prestigio_confirmar", "¿Seguro? Toca otra vez" },
            { "ui_prestigio_falta_piedra", "Falta crear la Piedra Filosofal" },
            { "ui_prestigio_falta_esencia", "Falta Esencia histórica (1 M)" },
            { "ui_prestigio_falta_gain", "Aún no hay Quintaesencia nueva que ganar" },
            { "ui_logro", "¡Logro!" },
            { "ui_ajuste_calidad", "Calidad gráfica" },
            { "ui_calidad_rendimiento", "Alto rendimiento" },
            { "ui_calidad_alta", "Máxima calidad" },
            { "ui_ajuste_sonido", "Sonido" },
            { "ui_sonido_on", "Activado" },
            { "ui_sonido_off", "Silenciado" },
            { "ui_ajuste_info", "Hecho con Unity · Las novedades llegan solas al abrir el juego" },
            { "ui_reset", "Borrar progreso" },
            { "ui_reset_confirmar", "¿SEGURO? Se pierde todo" },
            { "ui_offline_titulo", "Mientras estabas fuera..." },
            { "ui_offline_texto", "Tus ayudantes generaron el equivalente a:" },
            { "ui_ok", "¡Genial!" },
            { "ui_comprar_modo", "Cantidad de compra:" },
            { "ui_max", "Máx" },
            { "ui_hint_sin_ayudantes", "Transmutá elementos y contratá tu primer ayudante" },
            { "ui_mejoras_titulo", "— Mejoras del laboratorio —" },
            { "ui_adquirida", "Adquirida" },
            { "ui_hito", "Hito:" },
            { "ui_vol_musica", "Música" },
            { "ui_vol_sfx", "Efectos" },
            { "ui_ajuste_vibracion", "Vibración" },
            { "ui_stat_dorados", "Matraces dorados" },
            { "ui_backup_titulo", "Copia de seguridad" },
            { "ui_copiar_save", "Copiar guardado" },
            { "ui_pegar_save", "Pegar" },
            { "ui_pegar_confirmar", "¿Sobrescribir?" },
            { "ui_copiado", "¡Copiado!" },
            { "ui_cargado", "¡Cargado!" },
            { "ui_invalido", "Inválido" },
            { "ui_objetivo", "Objetivo" },
            { "ui_objetivo_ok", "¡Objetivo cumplido!" },
            { "ui_stats_titulo", "Estadísticas" },
            { "ui_stat_tiempo", "Tiempo jugado" },
            { "ui_stat_clicks", "Toques al matraz" },
            { "ui_stat_esencia", "Esencia histórica" },
            { "ui_stat_elementos", "Elementos descubiertos" },
            { "ui_stat_logros", "Logros" },
        };

        public static string T(string key) =>
            es.TryGetValue(key, out var v) ? v : key;
    }
}
